version: "3.8"

name: crud-with-cache

include:
  - infra.yml

services:
  crud:
    working_dir: /app
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app_network
    volumes:
      - "..:/app:delegated"
    command: air -build.poll true -c ./app/crud/main/.air.toml
    depends_on:
      mysql:
        condition: service_healthy
      cache:
        condition: service_started
      buffer:
        condition: service_started
      subscriber:
        condition: service_started
  subscriber:
    working_dir: /app
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    restart: always
    networks:
      - app_network
    volumes:
      - "..:/app:delegated"
    command: air -build.poll true -c ./app/subscriber/main/.air.toml
    depends_on:
      mysql:
        condition: service_healthy
      cache:
        condition: service_started
      buffer:
        condition: service_started