version: "3.8"

name: crud-with-cache

include:
  - infra.yml

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app_network
    depends_on:
      - mysql
      - redis
