version: "3.8"

name: crud-with-cache

include:
  - infra.yml

services:
  app:
    working_dir: /app
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app_network
    volumes:
      - "..:/app:delegated"
    command: air -build.poll true
    depends_on:
      - mysql
      - redis
